spring.application.name=identity-service
server.port=${PORT:8081}
server.forward-headers-strategy=${FORWARD_HEADERS_STRATEGY:framework}

# JWT
jwt.issuer=${JWT_ISSUER:http://localhost:8081}
jwt.access-token-ttl-minutes=${JWT_ACCESS_TTL_MIN:15}
jwt.refresh-token-ttl-days=${JWT_REFRESH_TTL_DAYS:30}

# RSA key locations (dev default = local non-committed files)
security.rsa.private-key-path=${JWT_PRIVATE_KEY_PATH:file:./.secrets/private.pem}
security.rsa.public-key-path=${JWT_PUBLIC_KEY_PATH:file:./.secrets/public.pem}


# CORS (mainly for Expo Web)
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:8083,http://localhost:19006}

# Rate limiting
app.ratelimit.enabled=${RATE_LIMIT_ENABLED:true}
app.ratelimit.login-per-minute=${RATE_LIMIT_LOGIN_PER_MINUTE:10}
app.ratelimit.register-per-minute=${RATE_LIMIT_REGISTER_PER_MINUTE:5}
app.ratelimit.refresh-per-minute=${RATE_LIMIT_REFRESH_PER_MINUTE:30}
app.ratelimit.logout-per-minute=${RATE_LIMIT_LOGOUT_PER_MINUTE:60}
app.ratelimit.jwks-per-minute=${RATE_LIMIT_JWKS_PER_MINUTE:120}

# Sentry
sentry.dsn=${SENTRY_DSN:}
sentry.environment=${SENTRY_ENVIRONMENT:development}
sentry.release=${SENTRY_RELEASE:}
sentry.traces-sample-rate=${SENTRY_TRACES_SAMPLE_RATE:0.0}

# Include request-id (MDC key "requestId") in log level section
logging.pattern.level=%5p [rid:%X{requestId:-}]
