package com.mealflow.appapi.inspiration.provider;

import com.fasterxml.jackson.annotation.JsonProperty;

public record MealDbMeal(
        @JsonProperty("idMeal") String id,
        @JsonProperty("strMeal") String title,
        @JsonProperty("strMealThumb") String imageUrl,
        @JsonProperty("strCategory") String category,
        @JsonProperty("strArea") String area,
        @JsonProperty("strInstructions") String instructions,
        @JsonProperty("strSource") String sourceUrl,
        @JsonProperty("strYoutube") String youtubeUrl,
        @JsonProperty("strIngredient1") String ingredient1,
        @JsonProperty("strIngredient2") String ingredient2,
        @JsonProperty("strIngredient3") String ingredient3,
        @JsonProperty("strIngredient4") String ingredient4,
        @JsonProperty("strIngredient5") String ingredient5,
        @JsonProperty("strIngredient6") String ingredient6,
        @JsonProperty("strIngredient7") String ingredient7,
        @JsonProperty("strIngredient8") String ingredient8,
        @JsonProperty("strIngredient9") String ingredient9,
        @JsonProperty("strIngredient10") String ingredient10,
        @JsonProperty("strIngredient11") String ingredient11,
        @JsonProperty("strIngredient12") String ingredient12,
        @JsonProperty("strIngredient13") String ingredient13,
        @JsonProperty("strIngredient14") String ingredient14,
        @JsonProperty("strIngredient15") String ingredient15,
        @JsonProperty("strIngredient16") String ingredient16,
        @JsonProperty("strIngredient17") String ingredient17,
        @JsonProperty("strIngredient18") String ingredient18,
        @JsonProperty("strIngredient19") String ingredient19,
        @JsonProperty("strIngredient20") String ingredient20,
        @JsonProperty("strMeasure1") String measure1,
        @JsonProperty("strMeasure2") String measure2,
        @JsonProperty("strMeasure3") String measure3,
        @JsonProperty("strMeasure4") String measure4,
        @JsonProperty("strMeasure5") String measure5,
        @JsonProperty("strMeasure6") String measure6,
        @JsonProperty("strMeasure7") String measure7,
        @JsonProperty("strMeasure8") String measure8,
        @JsonProperty("strMeasure9") String measure9,
        @JsonProperty("strMeasure10") String measure10,
        @JsonProperty("strMeasure11") String measure11,
        @JsonProperty("strMeasure12") String measure12,
        @JsonProperty("strMeasure13") String measure13,
        @JsonProperty("strMeasure14") String measure14,
        @JsonProperty("strMeasure15") String measure15,
        @JsonProperty("strMeasure16") String measure16,
        @JsonProperty("strMeasure17") String measure17,
        @JsonProperty("strMeasure18") String measure18,
        @JsonProperty("strMeasure19") String measure19,
        @JsonProperty("strMeasure20") String measure20) {}
